name: deploy-firebase-on-push-to-master
on:
  push:
    branches:
      - pay-demo-site

jobs:
  deploy:
    name: Deploy to Firebase
    runs-on: ubuntu-18.04
    container: node:14.0.0-alpine3.10

    steps:
      - uses: actions/checkout@v2

      - name: Install Firebase tools
        run: npm install -g firebase-tools

      - name: Perform deploy
        run: |
          firebase deploy --only hosting:pay-demo --non-interactive \
          -m "Deployment for commit SHA: $GITHUB_SHA" \
          --token ${{ secrets.FIREBASE_DEPLOY_TOKEN }}
